sass:
  style: compressed

# Site settings
title: Jelly
description: An example site

# Build settings
markdown: kramdown

baseurl: /website

# Timezone
timezone: GB

# Custom Collections

collections:
  events:
    output: true
    permalink: /event/:path/

# Configuration for prose.io online editor
prose:
  ignore: ['_includes','assets','_assets','_layouts','_plugins','/.jekyll-metadata','feed.xml','bin','js','css','_sass','.gitignore','Gemfile','Gemfile.lock','LICENSE.md','README.md']
  media: img
  metadata:
    _posts:
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: false
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
    _events:
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: false
      - name: "startdate"
        field:
          label: "Start Date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "layout"
        field:
          element: "hidden"
          value: "default"