sass:
  style: compressed

# Site settings
title: Jelly
description: An example site

# Build settings
markdown: kramdown

baseurl: http://aylestoneallotments.github.io/website

permalink: pretty

# Timezone
timezone: GB

# Custom Collections

collections:
  events:
    output: true
    permalink: /events/:year/:month/:day/:title/

# Configuration for prose.io online editor
prose:
  ignore: ['_includes','assets','_assets','_layouts','_plugins','/.jekyll-metadata','feed.xml','bin','js','css','_sass','_config.yml']
  media: img
  metadata:
    _posts:
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: false
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
    _events:
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: 2012-12-22 14:07
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: false
      - name: "layout"
        field:
          element: "hidden"
          value: "default"