sass:
  style: compressed

#  Build settings
markdown: kramdown

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
   
#  Site settings
title: Aylestone Allotments & Leisure Gardener's Society'
description: We are one of the oldest allotment societies in Leicester. We work to promote gardening and vegetable growing.
url: http://www.aylestoneallotments.co.uk
baseurl: 
email: newsletter@aylestoneallotments.co.uk
github: aylestoneallotments/www.aylestoneallotments.co.uk
logo_path: /img/logo.svg
copyright: "Copyright 2011 Aylestone Allotments and Leisure Gardeners Society."

# Opengraph settings

twitterimg: "/img/social/twitter-image.png"
ogimg: "/img/social/og-image.jpg"

#  Social media settings

facebook: "Aylestone-Allotments-and-Leisure-Gardeners-Society-AALGS-203607403321766/"
twitter : ""
instagram: ""

permalink: pretty

analyticstracking: "UA-77679948-1"

paginate: 5
paginate_path: "/news/:num/"

#  Timezone
timezone: Europe/London

exclude: ['bower.json']

#  Configuration for prose.io online editor
prose:
  ignore: ['_includes','assets','_assets','_layouts','_plugins','/.jekyll-metadata','feed.xml','bin','js','css','_sass','_config.yml','bower.json']
  media: img
  metadata:
    _posts:
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: false
      - name: "layout"
        field:
          element: "hidden"
          value: "default"