sass:
  style: compressed

#  Build settings
markdown: kramdown

#  Site settings
title: Aylestone Allotments and Leisure Gardener's Society
description: An example site
url: http://aylestoneallotments.github.io
baseurl: /website
email: newsletter@aylestoneallotments.co.uk

#  Social media settings

facebook: https://www.facebook.com/Aylestone-Allotments-and-Leisure-Gardeners-Society-AALGS-203607403321766/
twitter : tigefa_team
facebook: tigefa.team
permalink: pretty

analyticstracking: "UA-35898440-1"

#  Timezone
timezone: GB

#  Custom Collections

collections:
  events:
    output: true
    permalink: /events/:year/:month/:day/:title/

#  Configuration for prose.io online editor
prose:
  ignore: ['_includes','assets','_assets','_layouts','_plugins','/.jekyll-metadata','feed.xml','bin','js','css','_sass','_config.yml']
  media: img
  metadata:
    _posts:
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: false
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
    _events:
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: 2012-12-22 14:07
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: false
      - name: "layout"
        field:
          element: "hidden"
          value: "default"