  # This file contains details of people in the organisation.
  #
  # Options:
  # - name: "name of the person"
  #   img: "path to picture of person relative baseurl"
  #   role: "role of person within organisation"
  #   phone: "telephone number"
  #   email: "email address of person"
  #   website: "presonal website of person"
  - name: "Malcolm Roberts"
    img: "/img/profiles/profile-placeholder.gif"
    role: "Acting Secretary"
    phone: "Profile phone"
    email: "aalsgcsec@yahoo.co.uk"
  - name: "Glenys Langston"
    img: "/img/profiles/glenys.jpg"
    role: "Treasurer"
  - name: "Peter Loseby"
    img: "/img/profiles/peter.jpg"
    role: "Social Secretary"
    email: "newsletter@aylestoneallotments.co.uk"
  - name: "Richard Scott"
    img: "/img/profiles/profile-placeholder.gif"
    role: "Newsletter & Website Team Member"
    email: "newsletter@aylestoneallotments.co.uk"